# ===============================
# SecureBank Application
# ===============================

app.name=SecureBank

app.version=1.0

server.port=8080

# ===============================
# Database (Enable Later)
# ===============================

db.driver=com.mysql.cj.jdbc.Driver

db.url=jdbc:mysql://localhost:3306/securebank_db

db.username=root

db.password=root

# ===============================
# Logging
# ===============================

log.level=INFO

# ===============================
# Session
# ===============================

session.timeout=30